server:
  port: 8080

spring:
  application:
    name: spring-ai-demo
  ai:
    retry:
      max-attempts: 5
      backoff:
        initial-interval: 2000ms
        multiplier: 2
        max-interval: 30000ms
    openai:
      api-key: ${GEMINI_KEY}
      chat:
        base-url: https://generativelanguage.googleapis.com
        completions-path: /v1beta/openai/chat/completions
        options:
          model: gemini-2.0-flash
          temperature: 0.4
      embedding:
        base-url: https://generativelanguage.googleapis.com
        embeddings-path: /v1beta/openai/
        options:
          dimensions: 1536
          model: text-embedding-004
    vectorstore:
      pinecone:
        api-key: ${PINECONE_API_KEY}
        environment: us-east-1-aws
        index-name: spring-ai-demo
